# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ceasar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import os
os.environ['QT_OPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 368)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.encryptbtn = QtWidgets.QPushButton(self.centralwidget)
        self.encryptbtn.setGeometry(QtCore.QRect(80, 280, 75, 23))
        self.encryptbtn.setObjectName("encryptbtn")
        self.decryptbtn = QtWidgets.QPushButton(self.centralwidget)
        self.decryptbtn.setGeometry(QtCore.QRect(360, 280, 75, 23))
        self.decryptbtn.setObjectName("decryptbtn")
        self.plaintext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plaintext.setGeometry(QtCore.QRect(110, 20, 321, 71))
        self.plaintext.setObjectName("plaintext")
        self.ciphertext = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.ciphertext.setGeometry(QtCore.QRect(110, 170, 321, 71))
        self.ciphertext.setObjectName("ciphertext")
        self.key = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(110, 110, 321, 31))
        self.key.setObjectName("key")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 120, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 200, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.encryptbtn.setText(_translate("MainWindow", "Encrypt"))
        self.decryptbtn.setText(_translate("MainWindow", "Decrypt"))
        self.label.setText(_translate("MainWindow", "Plain text"))
        self.label_2.setText(_translate("MainWindow", "key"))
        self.label_3.setText(_translate("MainWindow", "Cipher text"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
